[project]
name = "hpa"
version = "0.0.1"
dynamic = ["dependencies"]

[build-system]
requires = ["setuptools>=62.6"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
